[package]
name = "comics"
version = "2.0.0"
edition = "2021"
authors = ["henry40408 <2316687+henry40408@users.noreply.github.com>"]
description = "Simple file server for comic books"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.1"
axum = "0.6.20"
base64 = "0.21.5"
bcrypt = "0.15.0"
blake3 = "1.5.0"
chrono = "0.4.31"
clap = { version = "4.4.3", features = ["derive", "env"] }
hyper = "0.14.27"
image = { version = "0.24.7", default-features = false, features = [
  "png",
  "jpeg",
] }
infer = "0.15.0"
rand = "0.8.5"
rpassword = "7.2.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.4.4", features = ["trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1.5.0", features = ["v4"] }

[dev-dependencies]
axum-test = "13.1.1"
cucumber = "0.20.1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true

[[test]]
name = "comics"
harness = false
