[package]
name = "comics"
version = "2.0.0"
edition = "2021"
authors = ["henry40408 <2316687+henry40408@users.noreply.github.com>"]
description = "Simple file server for comic books"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.0"
axum = "0.6.20"
base64 = "0.21.4"
bcrypt = "0.15.0"
blake3 = "1.5.0"
chrono = "0.4.31"
clap = { version = "4.4.3", features = ["derive", "env"] }
hyper = "0.14.27"
infer = "0.15.0"
rand = "0.8.5"
rpassword = "7.2.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.4.4", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[dev-dependencies]
axum-test = "12.4.0"
cucumber = "0.20.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
