[package]
name = "comics"
version = "0.1.0"
edition = "2021"
authors = ["henry40408 <2316687+henry40408@users.noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.0"
axum = "0.6.20"
base64 = "0.21.4"
bcrypt = "0.15.0"
chrono = "0.4.31"
clap = { version = "4.4.3", features = ["derive"] }
hyper = "0.14.27"
indexmap = "2.0.0"
infer = "0.15.0"
rpassword = "7.2.0"
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.4.4", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1.4.1", features = ["v4"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
