[licenses]
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "MIT",
  "Unicode-DFS-2016",
]

[advisories]
version = 2
ignore = [
  # used by axum-test, so the vulnerability won't affect the application.
  "RUSTSEC-2024-0421",
]
