on: [pull_request, push]

name: CI

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dtolnay/rust-toolchain@1.84.1
        with:
          components: clippy,rustfmt
      - uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo fmt --check
      - run: cargo clippy
      - uses: taiki-e/install-action@v2.39.1
        with:
          tool: cargo-deny@0.16.4
      - run: cargo deny check
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dtolnay/rust-toolchain@1.84.1
      - uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: taiki-e/install-action@v2.39.1
        with:
          tool: cargo-llvm-cov@0.6.14,cargo-nextest@0.9.87
      - run: cargo llvm-cov nextest --all-features --workspace --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v4.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: taiki-e/install-action@v2.39.1
        with:
          tool: cargo-hack@0.6.28
      - run: cargo hack check --rust-version --workspace --all-targets --ignore-private
  build-and-publish:
    needs: [check, coverage, msrv]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3.0.0
      - uses: docker/setup-buildx-action@v3.0.0
      - uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/henry40408/comics:nightly
        if: github.ref_type == 'branch' && github.ref_name == 'main'
      - uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/henry40408/comics:${{ github.ref_name }}
        if: github.ref_type == 'tag'
      - uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/henry40408/comics:latest
        if: github.ref_type == 'tag'
