on: [push, pull_request]

name: CI

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'
      - run: gofmt -l .

